---
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Swagger Petstore"
  license:
    name: "MIT"
servers:
- url: "http://localhost:8383/v1"
paths:
  /pets:
    get:
      summary: "List all pets"
      operationId: "listPets"
      tags:
      - "pets"
      parameters:
      - name: "limit"
        in: "query"
        description: "How many items to return at one time (max 99)"
        required: false
        schema:
          type: "integer"
          format: "int32"
      security:
      - petstore_auth:
        - "read:pets"
      responses:
        "200":
          description: "An paged array of pets"
          headers:
            x-next:
              description: "A link to the next page of responses"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Pet"
              example:
              - id: 1
                name: "catten"
                tag: "cat"
              - id: 2
                name: "doggy"
                tag: "dog"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: "Create a pet"
      operationId: "createPets"
      requestBody:
        description: "Pet to add to the store"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      tags:
      - "pets"
      security:
      - petstore_auth:
        - "read:pets"
        - "write:pets"
      responses:
        "201":
          description: "Null response"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: "Info for a specific pet"
      operationId: "showPetById"
      tags:
      - "pets"
      parameters:
      - name: "petId"
        in: "path"
        required: true
        description: "The id of the pet to retrieve"
        schema:
          type: "string"
      security:
      - petstore_auth:
        - "read:pets"
      responses:
        "200":
          description: "Expected response to a valid request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
              example:
                id: 1
                name: "Jessica Right"
                tag: "pet"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "Delete a specific pet"
      operationId: "deletePetById"
      tags:
      - "pets"
      parameters:
      - name: "petId"
        in: "path"
        required: true
        description: "The id of the pet to delete"
        schema:
          type: "string"
      - name: "key"
        in: "header"
        required: true
        description: "The key header"
        schema:
          type: "string"
      security:
      - petstore_auth:
        - "write:pets"
      responses:
        "200":
          description: "Expected response to a valid request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
              examples:
                response:
                  value:
                    id: 1
                    name: "Jessica Right"
                    tag: "pet"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /stores:
    get:
      summary: "List all pet stores while learn how to add new services"
      operationId: "listStores"
      tags:
      - "stores"
      parameters:
      - name: "limit"
        in: "query"
        description: "This service only return 10 stores"
        required: false
        schema:
          type: "integer"
          format: "int32"
      security:
      - petstore_auth:
        - "read:stores"
      responses:
        "200":
          description: "An paged array of stores"
          headers:
            x-next:
              description: "A link to the next page of responses"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Store"
              example:
              - id: "OTT_PETSMART_1"
                brand: "PETSMART"
                address: "99 Bank Street Ottawa HOHOHO"
              - id: "OTT_HAPPYPETS_7"
                brand: "HAPPYPETS"
                address: "100 Green Lane Nepean L0L0L0"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: "Add store"
      operationId: "addStore"
      requestBody:
        description: "Add new pet store"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Store"
      tags:
      - "stores"
      security:
      - petstore_auth:
        - "read:stores"
        - "write:stores"
      responses:
        "201":
          description: "Null response"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    petstore_auth:
      type: "oauth2"
      description: "This API uses OAuth 2 with the client credential grant flow."
      flows:
        clientCredentials:
          tokenUrl: "https://localhost:6882/token"
          scopes:
            write:pets: "modify pets in your account"
            write:stores: "add new store to inventory"
            read:pets: "read your pets"
            read:stores: "see list of stores"
  schemas:
    Pet:
      type: "object"
      required:
      - "id"
      - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        tag:
          type: "string"
    Store:
      type: "object"
      required:
      - "id"
      - "brand"
      - "address"
      properties:
        id:
          type: "string"
        brand:
          type: "string"
        address:
          type: "string"
    Error:
      type: "object"
      required:
      - "code"
      - "message"
      properties:
        code:
          type: "integer"
          format: "int32"
        message:
          type: "string"
